name: Hello World üåç

on:
  push:

jobs:
  hello-job:
    name: Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: My first step in GH Actions
        run: echo Hello action on ${{ github.event_name }}

      - name: Second GH Actions step by ${{ github.actor }}
        "run": "echo Hello action in ${{ github.repository }} ref: ${{ github.ref }}"

      - name: This GH Action is running on ${{ runner.os }}
        "run": "echo Action job status: ${{ job.status }}"
